DROP TABLE CITIZEN CASCADE CONSTRAINTS;
DROP TABLE PASSPORT CASCADE CONSTRAINTS;
DROP TABLE PHONENUMBER CASCADE CONSTRAINTS;
DROP TABLE STATEOFP CASCADE CONSTRAINTS;
DROP TABLE TYPE_OF_PASSPORT CASCADE CONSTRAINTS;
DROP VIEW PASSPORT_INFORMATION;